name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    env:
      IMAGE_TAG: make-flippy:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Pull msw/servercore
        run: docker pull mcr.microsoft.com/windows/servercore:ltsc2022-amd64

      - name: Build the Docker Image
        run: |
          docker build -f Dockerfile -t $env:IMAGE_TAG .

      - name: Create Docker Container
        shell: powershell
        run: |
          $containerId = docker create $env:IMAGE_TAG
          echo "CONTAINER_ID=$containerId" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Write-Host "Created Container ID: $containerId"

      - name: Verify Container ID
        shell: powershell
        run: |
          Write-Host "Using Container ID: $env:CONTAINER_ID"

      - name: Copy Plugin Directory from Docker Container
        shell: powershell
        run: |
          docker cp $env:CONTAINER_ID:/build/bl_flip_fluids/flip_fluids_addon ./flip_fluids

      - name: Zip the Plugin Directory
        shell: powershell
        run: |
          Compress-Archive -Path flip_fluids -DestinationPath flip_fluids.zip

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flip_fluids
          path: flip_fluids.zip

      - name: Cleanup Docker Container
        shell: powershell
        run: |
          docker rm $env:CONTAINER_ID
