name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    env:
      IMAGE_TAG: make-flippy:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Pull msw/servercore
        run: docker pull mcr.microsoft.com/windows/servercore:ltsc2022-amd64

      - name: Build the Docker Image
        run: |
          docker build -f Dockerfile -t $env:IMAGE_TAG .

      - name: Run the Docker Image
        run: |
          docker run $env:IMAGE_TAG

      - name: Copy Plugin Directory from Docker Container
        shell: powershell
        run: |
          docker cp "$(docker ps -aq --filter "ancestor=$env:IMAGE_TAG"):/flop/build/bl_flip_fluids/flip_fluids_addon" "./flip_fluids"

      - name: Zip the Plugin Directory
        shell: powershell
        run: |
          Compress-Archive -Path flip_fluids -DestinationPath flip_fluids.zip

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flip_fluids
          path: flip_fluids.zip
