name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    env:
      IMAGE_TAG: make-flippy:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Pull msw/servercore
        run: docker pull mcr.microsoft.com/windows/servercore:ltsc2022-amd64

      - name: Build the Docker Image
        run: |
          docker build . \
          -f Dockerfile \
          -t $IMAGE_TAG

      - name: Create Docker Container
        id: create-container
        run: |
          CONTAINER_ID=$(docker create $IMAGE_TAG)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

      - name: Copy Plugin Directory from Docker Container
        run: |
          docker cp ${{ env.CONTAINER_ID }}:/build/bl_flip_fluids/flip_fluids_addon ./flip_fluids

      - name: Zip the Plugin Directory
        run: |
          zip -r flip_fluids.zip flip_fluids

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flip_fluids
          path: flip_fluids.zip

      - name: Cleanup Docker Container
        run: |
          docker rm ${{ env.CONTAINER_ID }}
